name: build

on: [push]

jobs:
  build_executables:
    name: build standalone executable binaries with Nuitka
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install Python
        uses: actions/setup-python@v2
      - name: install dependencies
        run: pip install nuitka .
      - name: build executable
        run: python -m nuitka packetraven/__main__.py --standalone --onefile --enable-plugin=numpy
      - name: save wheel
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./dist/*.whl
