name: build

on: [push]

jobs:
  build_executables:
    name: build standalone executable binaries with pyinstaller
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install Python
        uses: actions/setup-python@v2
      - name: install dependencies
        run: pip install pyinstaller .
      - name: build executable
        run: python -m pyinstaller packetraven/packetraven.py --onefile
      - name: save executable
        uses: actions/upload-artifact@v2
        with:
          name: executable
          path: ./dist/*
